Fix: permissions on channels requests
strawberry-graphql/strawberry-django pull request #331
Opened 2023-08-07 14:18 UTC by nrbnlulu

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

fix #330 

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-08-07 17:12 UTC, bellini666 requested changes
The PR is mostly fine! :)

Left a small suggestion, will take a look again when the PR is ready to be reviewed

2023-08-07 17:12 UTC, bellini666 commented on tests/test_permissions.py
> +async def test_channels_authenticated(
Would be nice to have tests for both authenticated and non-authenticated (which would fail) for this

2024-01-25 21:02 UTC, nrbnlulu commented on strawberry_django/permissions.py
> +            user = info.context["request"].user
When I wrote this PR context wasn't a dict on HTTP requests.

2024-01-25 21:10 UTC, sdobbelaere commented on strawberry_django/permissions.py
> +            user = info.context["request"].user
You may want to use:

```
from strawberry_django.auth.utls import get_current_user
user = get_current_user(info)
```

2025-04-04 15:47 UTC, bellini666 commented
🧹 closing this as it is very outdated

Feel free to ping me if you want this reopened, or simply open a new PR 😊

2025-04-04 15:47 UTC, closed without merging