Deduce model field names from custom prefetches
strawberry-graphql/strawberry-django pull request #473
Opened 2024-02-05 21:42 UTC by diesieben07

## Description

Currently the QuerySet optimizer is oblivious to custom `prefetch_related` like the following:
```python
@strawberry_django.type(models.Project)
class ProjectType(models.Project):
      @strawberry_django.field(
        prefetch_related=lambda _: Prefetch(
            "milestones",
            to_attr="next_milestones_pf",
            queryset=Milestone.objects.filter(due_date__isnull=False).order_by("due_date")
        )
    )
    def next_milestones(self) -> "list[MilestoneType]":
        return self.next_milestones_pf
```

The current optimizer cannot understand how to optimize "through" this prefetch, because it cannot find the model field (`milestones` in `Project`) that the field uses.
This results in the optimization essentially stopping at the `next_milestones` field and any further nested relations will cause N+1 issues.

This pull request attempts to address this shortcoming.

## Types of Changes

Now the optimizer first inspects the field configuration to find any custom `Prefetch`. A custom prefetch is one which has a custom `to_attr`  set. The optimizer then uses these custom Prefetches to perform further optimization instead of stopping here.

- [ ] Core
- [ ] Bugfix
- [X] New feature
- [X] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

* https://github.com/strawberry-graphql/strawberry-graphql-django/issues/389

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the CONTRIBUTING document.
- [X] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-02-05 21:49 UTC, diesieben07 commented
Some guidance on the test failures would be great. I am not 100% sure what the correct approach would be for the changed GraphQL schema.

2024-03-03 15:35 UTC, bellini666 requested changes
Wow, sorry for taking to long to review this. For some reason I started reviewing and stopped, had a some comments drafted...

> Some guidance on the test failures would be great. I am not 100% sure what the correct approach would be for the changed GraphQL schema.

Most of the issues I'm seeing here are related to typing. Try to run `pyright` locally and it will help you fix those. If you need specific guidance feel free to reach me on [discord](https://strawberry.rocks/discord) :)

There are some related to features not supported on older python versions. e.g. `X | Y` cannot be used yet because we are targeting python 3.8+, `Annotated` needs to be imported from `typing_extensions` (it was introduced on 3.9), etc

About the schema, just run pytest with `--snapshot-update` and it should update the schema file :)

2024-03-03 17:10 UTC, diesieben07 commented
@bellini666 I think all the linting and type errors should be resolved now and the snapshot test fixed.

2024-03-04 22:57 UTC, bellini666 requested changes
The solution don't seem to be working for django 3.2 and 4.0 (see the tests that broke)

2024-03-04 22:57 UTC, bellini666 commented on tests/projects/schema.py
> +    pass
Is this a left over from a test attempt? =P

This is not being used, so it should be removed

2025-03-18 12:58 UTC, diesieben07 commented
I tried to revive this yesterday, but decided to abandon this approach. Instead I will look into creating a different pull request that makes using `optimize` inside a custom prefetch function easier.

2025-03-18 12:58 UTC, closed without merging