Expose apply and OffsetPaginationInput publicly
strawberry-graphql/strawberry-django pull request #476
Opened 2024-02-07 09:46 UTC by fireteam99

## Description
Exposes `apply` and `OffsetPaginationInput` in `strawberry_django/__init__.py` to allow public access.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

* https://github.com/strawberry-graphql/strawberry-graphql-django/issues/470

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-02-07 18:46 UTC, fireteam99 commented on strawberry_django/__init__.py
> +    "apply",
@bellini666 what are your thoughts on aliasing `apply` to `apply_pagination`?

2024-02-07 22:38 UTC, bellini666 requested changes

2024-02-07 22:38 UTC, bellini666 commented on strawberry_django/__init__.py
> +    "apply",
TBH I'm not sure if we should be exposing `apply` here. We do expose `filters` and `ordering`, which are modules similar to `pagination`, so doing the same here should allow you to do:

```python
from strawberry_django import pagination

pagination.apply(...)
```

2024-02-09 18:25 UTC, fireteam99 commented on strawberry_django/__init__.py
> +    "apply",
Ahh good point your suggestion is much better! Will update and re-request!

2024-02-13 13:19 UTC, bellini666 approved these changes

2024-02-13 13:19 UTC, merged