feat: filter_field optional value resolution
strawberry-graphql/strawberry-django pull request #510
Opened 2024-03-26 13:23 UTC by Kitefiko

## Description
Adds option not to resolve value of custom filter method via `@strawberry_django.filter_field(resolve_value=False)`.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [x] Documentation

## Issues Fixed or Closed by This PR

* https://github.com/strawberry-graphql/strawberry-django/issues/509

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-03-30 21:29 UTC, bellini666 approved these changes
LGTM!

Before merging, I'm wondering if we should avoid resolving the value for custom filters by default? What do you think?

2024-03-30 21:32 UTC, bellini666 commented
@Kitefiko even looking at the example on the issue you created:

```python
@strawberry_django.filter_field
def multi_filter(self, value: relay.GlobalID):
    # value here is not GlobalID instance, but already resolved node_id (str)
    # so following cannot be currently done
    
    if value.type_name == "FruitNode":
        ...
    else value.type_name == "VegetableNode":
        ... 
    else:
        raise ValidationError("Incorrect GlobalID type")
```

It seems strange if `value` in this case is not actually `GlobalID`. i.e. the typing should be respected.

Do you think we can refactor this to basically only convert the value for automatic filters and pass it as is to custom resolvers, to make sure the type is respected?

2024-03-30 21:32 UTC, bellini666 requested changes
Changing this to `Request changes` because of my last comment

2024-03-31 08:14 UTC, Kitefiko commented
Hi,
yeah, that was precisely my question. 
So just to clear this up for me. You suggest to do breaking change and stop resolving value in custom filters. I assume still leaving the ability to use param to do so, but make it not resolve by default?

2024-03-31 16:48 UTC, bellini666 commented
> Hi, yeah, that was precisely my question. So just to clear this up for me. You suggest to do breaking change and stop resolving value in custom filters. I assume still leaving the ability to use param to do so, but make it not resolve by default? Another question I found during adjustments, should `RangeLookup` resolve its `start` and `end` fields?
> 
> Edit: Adjusted. Made `RangeLookup` resolve it's field.

Yes.

This is still a new change so I think it is safe

What I mean is that when I do something like this:

```python
@strawberry_django.filter_field()
def some_filter(self, value: relay.GlobalID, prefix: str) -> Q:
    ...
```

I expect that the `value` will be `GloabalID` as it is typed, and not its resolved value. Not `value` not being `GlobalID` just like it is typed there is a bug to IMO

Maybe we can have an option to opt-in to "automatic resolution" of the values, but TBH I think we don't even need that as it seems more confusing. What are your thoughts here?

2024-03-31 18:20 UTC, Kitefiko commented
Ok, so currently it is done as you describe BUT with opt-in `resolve_value` (more info in docs - I think it's pretty clear there). And also auto resolving for `RangeLookup` - still don't know, whether this is good choice.

I would probably leave `resolve_value` in? Don't really see reason to rip it out, there might be use-case (custom GlobalID?, different enum value resolution?) for custom Lookups where value resolution might be unwanted and this covers that.

2024-04-01 21:39 UTC, bellini666 approved these changes
Thank you! :)

2024-04-01 21:40 UTC, merged